site_name: Def

theme: 
 name: material
 palette:
  scheme: slate
  primary: deep orange
  accent: deep orange
 icon:
  logo: material/bottle-tonic-skull
 favicon: material/bottle-tonic-skull
 font: Roboto Mono
