site_name: ==Def==
repo_url: https://github.com/torrentcome/def
site_url: https://github.com/torrentcome/def

theme: 
 name: material
 palette:
  primary: indigo
  accent: lime
 icon:
  logo: material/bottle-tonic-skull
 favicon: material/bottle-tonic-skull
