site_name: Def

theme: 
 name: material
 palette:
  scheme: default
  primary: black
  accent: indigo
 icon:
  logo: material/android-debug-bridge
 favicon: material/android-debug-bridge
 font: Roboto Mono
