site_name: Def

theme: 
 name: material
 palette:
  scheme: slate
  primary: indigo
  accent: indigo
 icon:
  logo: material/bottle-tonic-skull
 favicon: material/bottle-tonic-skull
 font: Roboto Mono
